### ISSUE TITLE
Include more template projects

### ISSUE THREAD

**Issue by itsaky** [itsaky/AndroidIDE#14]
Some template suggestions :
- [x] Kotlin project
- [x] LibGdx Project
- [x] Project with material design components

Maybe we can include an option to choose the root layout for the default activity_main.xml?

**Comment by masterjavaofficial** [comment]
> Maybe we can include an option to choose the root layout for the default activity_main.xml?

Try to do the same like Android Studio. Does Studio asks for the root layout? No.

**Comment by itsaky** [comment]
Yeah. You're right. That's not a good idea.

However, it doesn't necessarily have to be same like Android Studio.

**Comment by masterjavaofficial** [comment]
> However, it doesn't necessarily have to be same like Android Studio.

Hmm. But you need not build a copy of the Android Studio that will be running on Android platform! Just try to add as much features as you can. If you follow the Android Studio environment while building, it will help Studio users to adopt your app easily, so that they can use it on the go.

Also consider making the project open-source, since doing this will take more attention and attraction of Android devs. Inhancement and fixes will also come fast.

**Comment by itsaky** [comment]
> Just try to add as much features as you can.

Yeah, sure. If you have suggestions, do open a feature request here.

> Also consider making the project open-source, since doing this will take more attention and attraction of Android devs. Inhancement and fixes will also come fast from the community.

We'll think about it. Thanks for the suggestion.

**Comment by anonimo82** [comment]
Sorry for necro posting, but I'd like the LibGDX project generation options to include choices for (at least) physics and AI (Box2D or Bullet, and LibGDX-AI) and why not, gltf?

Thanks
