### ISSUE TITLE
Heap Pointer issue on Android 12

### ISSUE THREAD

**Issue by KuatoDev** [itsaky/AndroidIDE#28]
![Screenshot_20211210-184155_AndroidIDE](https://user-images.githubusercontent.com/17999613/145575771-db3851ac-c5ea-4d27-9baa-a53348263a31.png)

**Comment by itsaky** [comment]
Try using [OpenJDK 17](https://github.com/itsaky/openjdk-17) (download from releases).

**Comment by Etanarvazac** [comment]
**Describe the bug**
I provided version 7.3.3 and recieved this error on a new project:
```
-------------------- NOTE --------------------
Gradle Wrapper is not available!
Installing default one. Gradle v7.1.1 will be downloaded if necessary.
----------------------------------------------
========== [10:41:50] TASK_BEGIN: assembleDebug ==========
ERROR: could not disable heap pointer tagging, Operation not supported on transport endpoint
gradlew: eval: line 2: :app:assembleDebug: not found
gradlew: eval: line 4: --init-script: not found
ERROR: could not disable heap pointer tagging, Operation not supported on transport endpoint
/data/data/com.itsaky.androidide/files/init/androidide.init.gradle: line 1: import: not found
/data/data/com.itsaky.androidide/files/init/androidide.init.gradle: line 2: import: not found
/data/data/com.itsaky.androidide/files/init/androidide.init.gradle: line 3: import: not found
/data/data/com.itsaky.androidide/files/init/androidide.init.gradle: line 5: gradle.projectsLoaded: not found
/data/data/com.itsaky.androidide/files/init/androidide.init.gradle: line 7: syntax error: unexpected newline
gradlew: eval: line 8: --info: not found
ERROR: could not disable heap pointer tagging, Operation not supported on transport endpoint
Downloading https://services.gradle.org/distributions/gradle-7.1.1-bin.zip
..........10%...........20%...........30%..........40%...........50%...........60%..........70%...........80%...........90%...........100%

Welcome to Gradle 7.1.1!

Here are the highlights of this release:
- Faster incremental Java compilation
- Easier source set configuration in the Kotlin DSL

For more details see https://docs.gradle.org/7.1.1/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Project 'ERROR' not found in root project 'appBuild1'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6m 39s
```
Then the Gradle output gets stuck in this loop:
![SmartSelect_20220103-105144_AndroidIDE.jpg](https://user-images.githubusercontent.com/55290878/147951352-19fb5d79-07ea-40b5-95b4-5b92b2a63557.jpg)
This attempt ran for 6 minutes, 39 seconds

**To Reproduce**
Steps to reproduce the behavior:
1. Using a fresh install of IDE, provide it the build tools needed:
![SmartSelect_20220103-103857_X-plore.jpg](https://user-images.githubusercontent.com/55290878/147950771-b22d523a-b7a4-464c-a8b9-0e0cc81bfe06.jpg)
![Screenshot_20220103-103953_AndroidIDE.jpg](https://user-images.githubusercontent.com/55290878/147950798-c473b470-892c-411c-87a9-5340c24db66d.jpg)
2. Start a new project.

**Expected behavior**
Build suceeds and you can start building app.

**Screenshots**
(Provided above)

**Details (please complete the following information):**
 - Device: Samsung Galaxy S21 5G
 - OS: Android 12
 - AndroidIDE Version 1.0.3-alpha for arm64-v8a

**Additional context**
All screenshots provided show versioning of each file (as recieved from `androidide` and `gradle.org`. Spite the more detail with 2 issues addressed, here is everything typed into #40..... So whether this is a `heap pointer` issue or simply Gradle versioning (as seen above, IDE downloaded 7.1.1 spite having installed 7.3.3 on startup), I don't know.....

**Comment by Etanarvazac** [comment]
@itsaky IDE is not accepting JDK/JRE 17

![SmartSelect_20220103-112000_AndroidIDE.jpg](https://user-images.githubusercontent.com/55290878/147954583-2aa0dfdb-9d4b-4f1e-b56b-dc7dff3335cb.jpg)
![SmartSelect_20220103-112150_AndroidIDE.jpg](https://user-images.githubusercontent.com/55290878/147954609-32ecb4ac-b7d4-4787-930c-ff8c8b3f54be.jpg)
Error: `No such file or directory`

**Comment by dhaigit** [comment]
The jdk17 packages above don't install correctly because they have a sub folder named "."

I compared those to the previous package (version 11) and the sub folder was named "jdk"

So I had to extract, rename, and repackage them, which would have been a lot easier if I did it on a linux machine (I used the app's terminal)

Everything installed sucessfully, but when trying to build an app, it failed. I used gradle wrapper.

If Gradle 7.1.1 was used, app failed with these errors:

FAILURE: Build failed with an exception.

* What went wrong:
Could not open init generic class cache for initialization script 'ROOT/init/data/common/androidide.init.gradle' (ROOT/framework/.gradle/caches/7.1.1/scripts/anzasx4u6ucsj6nvxgpw96v03).
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 61

So, I used Gradle 7.3.3 instead, but then got these errors:

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '/storage/emulated/0/AndroidIDEProjects/test1/app/build.gradle' line: 1

* What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin 'com.android.internal.application'.
> /data/.android

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* Where:
Initialization script 'ROOT/init/data/common/androidide.init.gradle' line: 50

* What went wrong:
A problem occurred configuring project ':app'.
> Failed to apply plugin class 'AndroidIDEPlugin'.
> Could not find method android() for arguments [AndroidIDEPlugin$_apply_closure1@65a764c1] on project ':app' of type org.gradle.api.Project.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

**Comment by itsaky** [comment]
Okay. I can reproduce the error. The openjdk-17 package (installed using ```pkg install openjdk-17```) also has some bugs.

So instead of rebuilding the [itsaky/openjdk-17](https://github.com/itsaky/openjdk-17), I'll rebuild the openjdk-17 package which can installed using the terminal.

**Comment by dhaigit** [comment]
Where does it install a local version of gradle? In caches? Could you modify the installation script so it would take an official gradle package (gradle-x.x.x-bin.zip or gradle-x.x.x-all.zip) and install it as a default local version?

Being able to use gradle wrapper is great, but can we also make the app fall back to a default pre-installed version whenever the gradle wrapper distribution url points to an invalid or not accessible location?

Every time I create a new project, I have to change the distributionUrl in gradle-wrapper.properties to point to my locally stored gradle-x.x.x-bin.zip, which isn't too bad, but is there an easier, automatic way?

**Comment by itsaky** [comment]
You can specify the folder where the Gradle Wrapper downloads the distributions using ```gradle-wrapper.properties``` file (defaults to ```$GRADLE_USER_HOME/wrapper/dists```). The IDE currently only supports the use of the ```gradlew``` script. But I'll add a preference for that. You'll be able to specify if you want to use the wrapper script or a default distribution and then specify path to that distribution.

And please open a new issue instead of discussing unrelated topics in other issues.

**Comment by dhaigit** [comment]
I saw that the original poster above was trying to get gradle to install as default. That was why I put that here.

I, or you, can remove or move it if you wish.

**Comment by itsaky** [comment]
> I saw that the original poster above was trying to get gradle to install as default.

Yes, I saw it. But that should not be the issue. The real issue here is :
> ERROR: could not disable heap pointer tagging, Operation not supported.

**Comment by itsaky** [comment]
@KuatoDev @dhaigit @Etanarvazac

The JDK 17 package has been updated. I have tested it's working by building a simple Android project.

To install the package, make sure you're using the APK from the [latest commit](https://github.com/itsaky/AndroidIDE/actions/runs/1677315887), then : 
- Open terminal
- Install the package using ```pkg in openjdk-17``` (170MB).

Now, you'll have to update the ```JAVA_HOME``` in ```ide-environment.properties```. To do this,
- Edit the file in terminal using
```
nano $SYSROOT/etc/ide-environment.properties
```

-  Make sure that the file has this entry
```
JAVA_HOME=$SYSROOT/opt/openjdk
```

**Comment by dhaigit** [comment]
Could you provide a direct link to download the package? I install/uninstall a lot of times, and also would like to be able to install it on devices where and when there is no active connection. So offline installation is important and needed.

**Comment by itsaky** [comment]
The packages are installed using the ```apt``` package manager (same as Termux's). So, packages are stored with ```.deb``` file extensions. You'll have to install that ```.deb``` file using ```dpkg -i <path_to_deb>```. Then you'll have to install the dependencies using ```apt satisfy openjdk-17``` (requires internet). You could download the ```.deb``` files of the dependencies too. But that would be a lot of work.

Direct download link for the OpenJDK's deb package is : 
- aarch64 : http://androidide.com/packages/dists/stable/main/binary-aarch64/openjdk-17_17.0-18_aarch64.deb
- arm       : http://androidide.com/packages/dists/stable/main/binary-arm/openjdk-17_17.0-18_arm.deb

**Comment by dhaigit** [comment]
Will you make it available the same way as the old jdk11-aarch64.tar.xz some time in the future, so that we could just stick it in an installation folder and let a freshly installed AndroidIDE take care of everything?

**Comment by Etanarvazac** [comment]
@itsaky Terminal is telling me the `pkg` command is not found. I looked at `help` and it's not listed.

![SmartSelect_20220111-215037_AndroidIDE.jpg](https://user-images.githubusercontent.com/55290878/149055182-585a8997-b223-4e84-b3e3-3d48849117db.jpg)

**Comment by Etanarvazac** [comment]
Using only the JDK17 and/or JRE17 files instead of the JDK11 returbed the `No such file or directory` loop. This screenshot is after several full re-installs of literally everything (including the latest APK, all build tools (64-bit))

![SmartSelect_20220111-220934_AndroidIDE.jpg](https://user-images.githubusercontent.com/55290878/149057499-6cc508dc-88d8-4ecb-87a4-fb5352ae6369.jpg)

**Comment by itsaky** [comment]
> Terminal is telling me the pkg command is not found. I looked at help and it's not listed.

Looks like you're using the old version of AndroidIDE. As I said earlier, you'll have to use a latest version.

> Using only the JDK17 and/or JRE17 files instead of the JDK11 returned the No such file or directory loop

I'll make the IDE independent of the JDK while installation. After I do this, you'll no longer have to use any JDK while first installation. You'll have to use the terminal to install JDK 17 after the installation.

**Comment by Etanarvazac** [comment]
I have re-installed AndroidIDE. But this is the only build listed:

![SmartSelect_20220112-081651_GitHub.jpg](https://user-images.githubusercontent.com/55290878/149147678-294836ee-2358-4bd8-8bcb-98be9e5875ad.jpg)

**Comment by dhaigit** [comment]
> I have re-installed AndroidIDE. But this is the only build listed:
>
He meant the newest apk build with the latest commit on here, and not the one currently on androidide.com

**Comment by Etanarvazac** [comment]
@dhaigit 1st screenshot is Github release. 2nd is the site.

**Comment by itsaky** [comment]
This is not I'm talking about. See [this](https://github.com/itsaky/AndroidIDE/actions/runs/1677315887).

Fo downloading APKs from commits, from the GitHub repo, go to `Actions`, then click the latest successful build, scroll down and download the APK.

**Comment by dhaigit** [comment]
@itsaky
> I'll make the IDE independent of the JDK while installation. After I do this, you'll no longer have to use any JDK while first installation. You'll have to use the terminal to install JDK 17 after the installation.
>
Would you please also update and rebuild your itsaky/openjdk-17. Then add a setting to take that release and install it, as an offline alternative to the online "pkg in openjdk-17" ?

**Comment by itsaky** [comment]
Yeah. Sure. But I'll do that at last. There are lot of issues/improvements I'm currently working on (specifically, terminal and java language server). That's why I decided to postpone the work related to UI Designer.

**Comment by itsaky** [comment]
Yes. UI Designer still has a lot of work left to do. So, of course, before the UI Designer.

**Comment by dhaigit** [comment]
> specifically, terminal and java language server
>
Yeah, auto completion, that's a killer, lol. Without a reliable, responsive, correctly working auto completion, we just can't use the IDE much more than a few minutes just to debug the IDE itself, or use it to build an already error-free project.

**Comment by itsaky** [comment]
@KuatoDev @Etanarvazac @dhaigit 

Did any of you face this error again when using JDK 17?

**Comment by Etanarvazac** [comment]
APK refused to install claiming the build was invalid. Sorry about the late reply

![SmartSelect_20220112-105011_Package installer.jpg](https://user-images.githubusercontent.com/55290878/150209849-34135ce2-98b2-47b5-8365-829214e250cd.jpg)

**Comment by Etanarvazac** [comment]
@itsaky I just tried again and got the same result.

![SmartSelect_20220119-155320_Package installer.jpg](https://user-images.githubusercontent.com/55290878/150212125-4ac7b4a1-f093-44c5-bc88-32727d2cb055.jpg)

**Comment by dhaigit** [comment]
I would have given some feedbacks but I'm currently using the IDE on an offline device. I just install the new build over the old version so it's still using openjdk-11. I hope the itsaky/openjdk-17 is getting updated soon.

You have too little time but a lot to do, I'm I right? Lol.

**Comment by itsaky** [comment]
@Etanarvazac If you were using the APK from the website earlier, you'll have to uninstall the previous version. This is because I changed the signing key when I made the project open source.

**Comment by Etanarvazac** [comment]
Now it tells me `Read-only file system`.

**Comment by itsaky** [comment]
Further discussions: #133.
