### ISSUE TITLE
doubletap/longpress one-word selection 

### ISSUE THREAD

**Issue by dhaigit** [itsaky/AndroidIDE#95]
Could we have doubletapping and longpressing select only one word as it was a couple of commits ago?

We should always start with one word as we only have "expand" and no "contract". It would mean we could never be able to select a single word without dragging the handles manually.

**Comment by itsaky** [comment]
This happens because the editor uses Android's `BreakIterator` on Android 24 and higher for selecting words on long press . See [this].(https://github.com/Rosemoe/sora-editor/blob/5014619f5e0712ed07bc12733d7d9df83077cd29/editor/src/main/java/io/github/rosemoe/sora/widget/EditorTouchEventHandler.java#L487)
